export { default as home } from './home'
export { default as logOut } from './log'
export { default as logPhoto } from './logPhoto'
export { default as logo } from './logo'
export { default as star } from './star'
export { default as loop } from './loop'
export { default as arrow } from './arrow'
